# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- scan
- lint
- test
- deploy

lint:app:frontend:
  stage: lint
  image: node:14-alpine
  script:
    - cd app/frontend
    - npm install --silent
    - npm run lint
  rules:
    - changes:
      - app/frontend/**/*

lint:app:backend:
  stage: lint
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2 # not sure if this is needed
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - cd app/backend/
    - docker build -t trailfunds-app-lint -f Dockerfile.app.prod --target lint .
    - docker run trailfunds-app-lint
  rules:
    - changes:
      - app/backend/**/*

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
