version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000

  nginx:
    build: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
