version: "3.9"

services:
  db:
    image: postgis/postgis

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    healthcheck:
      test: pg_isready -h db -U $$POSTGRES_USER -d postgres
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data

  api:
    build:
      context: .

    depends_on:
      db:
        condition: service_healthy
        restart: true

    restart: always

    env_file:
      - .env

    ports:
      - 5000:5000

    volumes:
      - .:/code/app

volumes:
  postgres:
