version: '3.9'

services:
  db:
    image: 861573826272.dkr.ecr.us-east-2.amazonaws.com/trailfunds-ecr-repo:postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data

  api:
    image: 861573826272.dkr.ecr.us-east-2.amazonaws.com/trailfunds-ecr-repo:api
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5000:5000

  nginx:
    image: 861573826272.dkr.ecr.us-east-2.amazonaws.com/trailfunds-ecr-repo:nginx
    build: ./nginx
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  postgres:
