version: '3.9'

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data

  api:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - .:/code/app

  nginx:
    build: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgres:
