version: '3.9'

services:
  postgres:
    image: postgis/postgis
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - .:/code/app

  # ngrok:
  #   image: wernight/ngrok
  #   restart: unless-stopped
  #   depends_on:
  #     - api
  #   command:
  #     - 'start'
  #     - '--all'
  #     - '--config'
  #     - '/etc/ngrok.yml'
  #   ports:
  #     - 4040:4040
  #   links:
  #     - api
  #   volumes:
  #     - ./.ngrok.yml:/etc/ngrok.yml
