version: '3.9'

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data

  api:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db

    volumes:
      - .:/code/app

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    links:
      - api
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    ports:
      - 4040:4040
      - 443:443
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml

volumes:
  postgres:
